#!/usr/bin/env bash
# One-command SaaS stack: Postgres + Redis + hardened API + static Studio.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

COMPOSE=(docker compose
  -f deploy/docker/docker-compose.yml
  -f deploy/docker/docker-compose.saas.yml
  --profile saas)

gen_secret() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 32
  else
    python3 -c 'import secrets; print(secrets.token_hex(32))'
  fi
}

ENV_FILE="${PLATFORM_ENV_FILE:-$ROOT/.env.saas}"
if [[ ! -f "$ENV_FILE" ]]; then
  echo "Creating $ENV_FILE with generated secrets…"
  cat >"$ENV_FILE" <<EOF
# Generated by scripts/saas-up.sh — do not commit.
PLATFORM_ENV=production
PLATFORM_SECRETS_KEY=$(gen_secret)
PLATFORM_AUTH_SECRET=$(gen_secret)
PLATFORM_ALLOW_DEV_LOGIN=false
PLATFORM_GOVERNOR_BACKEND=redis
PLATFORM_AUDIT_RETENTION_DAYS=90
PLATFORM_CORS_ORIGINS=http://localhost:8088,http://127.0.0.1:8088
PLATFORM_OIDC_REDIRECT_URI=http://localhost:8088/

# Optional real IdP (Okta / Azure AD / Keycloak):
# PLATFORM_OIDC_ISSUER=https://login.microsoftonline.com/<tenant-id>/v2.0
# PLATFORM_OIDC_CLIENT_ID=
# PLATFORM_OIDC_CLIENT_SECRET=
EOF
  echo "Wrote $ENV_FILE"
else
  echo "Using existing $ENV_FILE"
fi

# shellcheck disable=SC1090
set -a
source "$ENV_FILE"
set +a

if [[ -z "${PLATFORM_OIDC_ISSUER:-}" || -z "${PLATFORM_OIDC_CLIENT_ID:-}" ]]; then
  echo "NOTE: OIDC not configured — set PLATFORM_OIDC_* in $ENV_FILE for IdP login."
  echo "      For a local smoke test you can temporarily set PLATFORM_ALLOW_DEV_LOGIN=true"
  echo "      (production hardening will refuse that when PLATFORM_ENV=production)."
  if [[ "${PLATFORM_ALLOW_DEV_LOGIN:-false}" != "true" ]]; then
    echo "      Switching this run to PLATFORM_ENV=development so the API can boot without OIDC."
    export PLATFORM_ENV=development
    export PLATFORM_ALLOW_DEV_LOGIN=true
  fi
fi

echo "Building and starting SaaS profile…"
"${COMPOSE[@]}" --env-file "$ENV_FILE" up -d --build

echo "Waiting for API health…"
for _ in $(seq 1 60); do
  if curl -sf http://127.0.0.1:8080/health >/dev/null 2>&1; then
    break
  fi
  sleep 1
done

curl -sf http://127.0.0.1:8080/health | python3 -m json.tool || true
echo
echo "Studio:  http://127.0.0.1:8088/"
echo "API:     http://127.0.0.1:8080/health"
echo "Stop:    ${COMPOSE[*]} --env-file $ENV_FILE down"
